name: capstone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  arkit_plugin: ^1.0.7
  csv: ^5.1.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  image: ^4.1.6
  image_downloader_web: ^2.0.4
  image_picker: ^1.0.7
  image_size_getter: ^2.1.2
  stroke_text: ^0.0.2
  widgets_to_image: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
